### ISSUE TITLE
Build a reusable GitHub action

### ISSUE THREAD

**Issue by Eomm** [Eomm/statusboardify#6]
As a user, I want to be able to get a status board of my projects.

The usage would be like:

```
name: Statusboard

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  statusboard:
    uses: statusboardify@v1.0.0
    with:
      COMMIT_EMAIL: foo@bat.com
      COMMIT_NAME: Bot
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORIES_QUERY: "user:Eomm is:public"
      ISSUES_QUERY: "is:open"  
      PROJECT_REPOSITORY: https://github.com/Eomm/statusboardify
      SITE_NAME: 🚀 Eomm
      SITE_URL: https://github.com/Eomm
    permissions:
      contents: write
```

It should be doable by creating an `action.yml` with `type: composite`
